version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081" # Expose Expo dev server
      - "19000:19000" # Optional: Expo Metro Bundler
      - "19001:19001" # Optional: Expo debugger
      - "19002:19002" # Optional: Expo web UI
    volumes:
      - .:/app
      - /app/node_modules # Prevent overwriting node_modules inside container
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
